<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ann Lian">

<title>Analysis of Natural Resources and Conflict Clustering</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="final_3_files/libs/clipboard/clipboard.min.js"></script>
<script src="final_3_files/libs/quarto-html/quarto.js"></script>
<script src="final_3_files/libs/quarto-html/popper.min.js"></script>
<script src="final_3_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="final_3_files/libs/quarto-html/anchor.min.js"></script>
<link href="final_3_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="final_3_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="final_3_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="final_3_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="final_3_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#data-and-methods" id="toc-data-and-methods" class="nav-link" data-scroll-target="#data-and-methods">Data and Methods</a>
  <ul class="collapse">
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources">Data Sources</a>
  <ul class="collapse">
  <li><a href="#conflict-dataset" id="toc-conflict-dataset" class="nav-link" data-scroll-target="#conflict-dataset">Conflict Dataset</a></li>
  <li><a href="#resources-dataset" id="toc-resources-dataset" class="nav-link" data-scroll-target="#resources-dataset">Resources Dataset</a></li>
  </ul></li>
  <li><a href="#overview-of-conflict-dataset" id="toc-overview-of-conflict-dataset" class="nav-link" data-scroll-target="#overview-of-conflict-dataset">Overview of Conflict Dataset</a></li>
  <li><a href="#choropleth-map-of-conflict-fatalities" id="toc-choropleth-map-of-conflict-fatalities" class="nav-link" data-scroll-target="#choropleth-map-of-conflict-fatalities">Choropleth Map of Conflict Fatalities</a></li>
  <li><a href="#overview-of-resource-dataset" id="toc-overview-of-resource-dataset" class="nav-link" data-scroll-target="#overview-of-resource-dataset">Overview of Resource Dataset</a></li>
  <li><a href="#point-map-of-resources" id="toc-point-map-of-resources" class="nav-link" data-scroll-target="#point-map-of-resources">Point Map of Resources</a></li>
  </ul></li>
  <li><a href="#spatial-analysis" id="toc-spatial-analysis" class="nav-link" data-scroll-target="#spatial-analysis">Spatial Analysis</a>
  <ul class="collapse">
  <li><a href="#morans-i" id="toc-morans-i" class="nav-link" data-scroll-target="#morans-i">Moran’s I</a>
  <ul class="collapse">
  <li><a href="#global-morans-i-of-conflicts" id="toc-global-morans-i-of-conflicts" class="nav-link" data-scroll-target="#global-morans-i-of-conflicts">Global Moran’s I of Conflicts</a></li>
  <li><a href="#local-morans-i-of-conflicts" id="toc-local-morans-i-of-conflicts" class="nav-link" data-scroll-target="#local-morans-i-of-conflicts">Local Moran’s I of Conflicts</a></li>
  <li><a href="#global-morans-i-of-resources" id="toc-global-morans-i-of-resources" class="nav-link" data-scroll-target="#global-morans-i-of-resources">Global Moran’s I of Resources</a></li>
  <li><a href="#local-morans-i-of-resources" id="toc-local-morans-i-of-resources" class="nav-link" data-scroll-target="#local-morans-i-of-resources">Local Moran’s I of Resources</a></li>
  <li><a href="#compare-conflict-and-resource-data" id="toc-compare-conflict-and-resource-data" class="nav-link" data-scroll-target="#compare-conflict-and-resource-data">Compare conflict and resource data</a></li>
  </ul></li>
  <li><a href="#pairwise-correlation-function-pcf" id="toc-pairwise-correlation-function-pcf" class="nav-link" data-scroll-target="#pairwise-correlation-function-pcf">Pairwise Correlation Function (PCF)</a>
  <ul class="collapse">
  <li><a href="#pcf-of-observed-data" id="toc-pcf-of-observed-data" class="nav-link" data-scroll-target="#pcf-of-observed-data">PCF of Observed Data</a></li>
  <li><a href="#pcf-for-simulation" id="toc-pcf-for-simulation" class="nav-link" data-scroll-target="#pcf-for-simulation">PCF for Simulation</a></li>
  <li><a href="#compare-pcf-of-observed-data-and-simulation" id="toc-compare-pcf-of-observed-data-and-simulation" class="nav-link" data-scroll-target="#compare-pcf-of-observed-data-and-simulation">Compare PCF of Observed Data and Simulation</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#initial-conclusion" id="toc-initial-conclusion" class="nav-link" data-scroll-target="#initial-conclusion">Initial Conclusion</a>
  <ul class="collapse">
  <li><a href="#findings" id="toc-findings" class="nav-link" data-scroll-target="#findings">Findings</a></li>
  <li><a href="#implications" id="toc-implications" class="nav-link" data-scroll-target="#implications">Implications</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  <li><a href="#roadmap-for-further-exploration-and-refinement" id="toc-roadmap-for-further-exploration-and-refinement" class="nav-link" data-scroll-target="#roadmap-for-further-exploration-and-refinement">Roadmap for Further Exploration and Refinement</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis of Natural Resources and Conflict Clustering</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ann Lian </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>This project analyzes the relationship between international conflicts and natural resources. The hypothesis is that countries with higher concentrations of natural resources (e.g., oil fields, gas) are more likely to experience conflicts within a 50-km radius of the resource site.</p>
<p><strong>Type of Properties:</strong></p>
<ul>
<li><p><strong>First-order properties</strong>: Spatial intensity of conflicts around resource sites.</p></li>
<li><p><strong>Second-order properties</strong>: Spatial correlation between the locations of resources and conflicts.</p></li>
</ul>
<hr>
</section>
<section id="data-and-methods" class="level1">
<h1>Data and Methods</h1>
<section id="data-sources" class="level2">
<h2 class="anchored" data-anchor-id="data-sources">Data Sources</h2>
<section id="conflict-dataset" class="level3">
<h3 class="anchored" data-anchor-id="conflict-dataset">Conflict Dataset</h3>
<ul>
<li><strong>Source</strong>: Armed Conflict Location &amp; Event Data Project (ACLED).</li>
<li><strong>Date Range</strong>: 2022/01/01 - 2024/11/30.</li>
<li><strong>Focus</strong>: Conflict categories directly related to violent conflict or control of territory, often influenced by resource competition:
<ul>
<li>Armed Clash</li>
<li>Attack</li>
<li>Air/Drone Strike</li>
<li>Shelling/Artillery/Missile Attack</li>
<li>Non-State Actor Overtakes Territory</li>
<li>Government Regains Territory</li>
<li>Remote Explosive/Landmine/IED</li>
<li>Looting/Property Destruction</li>
</ul></li>
</ul>
</section>
<section id="resources-dataset" class="level3">
<h3 class="anchored" data-anchor-id="resources-dataset">Resources Dataset</h3>
<ul>
<li><strong>Source</strong>: Global Power Plant Database (Global Energy Observatory, Google, KTH Royal Institute of Technology).</li>
<li><strong>Last Updated</strong>: June 2021.</li>
</ul>
<hr>
</section>
</section>
<section id="overview-of-conflict-dataset" class="level2">
<h2 class="anchored" data-anchor-id="overview-of-conflict-dataset">Overview of Conflict Dataset</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Number of Rows:  446969 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of Columns:  9 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Column Names: 
 event_id_cnty year sub_event_type iso country location latitude longitude fatalities </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
First 5 Rows:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  event_id_cnty year   sub_event_type iso      country   location latitude
1      IRQ61163 2024 Air/drone strike 368         Iraq Gire Bahar  37.0992
2      YEM94292 2024      Armed clash 887        Yemen      Thaub  14.0794
3      BFO12923 2024           Attack 854 Burkina Faso     Barani  13.1691
4      BFO12944 2024 Air/drone strike 854 Burkina Faso      Bonou  13.1271
5      BFO12945 2024 Air/drone strike 854 Burkina Faso     Koroni  13.3106
  longitude fatalities
1   43.6066          0
2   44.0580          4
3   -3.8899          0
4   -2.8146          0
5   -3.9288         20</code></pre>
</div>
</div>
<p><strong>Description</strong> This dataset provides detailed information on conflict events from 2022 to 2024, including:</p>
<ul>
<li><p>Event details (event_id_cnty, year, sub_event_type).</p></li>
<li><p>Locations (latitude, longitude, country).</p></li>
<li><p>Severity captured through the fatalities variable.</p></li>
</ul>
</section>
<section id="choropleth-map-of-conflict-fatalities" class="level2">
<h2 class="anchored" data-anchor-id="choropleth-map-of-conflict-fatalities">Choropleth Map of Conflict Fatalities</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_3_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The choropleth map highlights conflict fatalities across countries during 2022–2024:</p>
<ol type="1">
<li><strong>Hotspots of Intense Conflict</strong>: Dark red shades indicate regions with higher fatalities, such as parts of the Middle East, South Asia, and Africa, reflecting ongoing conflicts or severe events.</li>
<li><strong>Low or No Fatalities</strong>: Light blue or gray shades represent countries with lower or no reported fatalities, suggesting relative stability.</li>
<li><strong>Global Conflict Patterns</strong>: The map effectively visualizes global conflict intensity, emphasizing hotspots where fatalities are concentrated.</li>
</ol>
<p>This visualization provides a clear overview of the geographic distribution and severity of conflict fatalities worldwide.</p>
</section>
<section id="overview-of-resource-dataset" class="level2">
<h2 class="anchored" data-anchor-id="overview-of-resource-dataset">Overview of Resource Dataset</h2>
<div class="cell" data-messge="false">
<div class="cell-output cell-output-stdout">
<pre><code>Number of Rows:  34936 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of Columns:  6 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Column Names: 
 country country_long capacity_mw latitude longitude primary_fuel </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
First 5 Rows:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  country country_long capacity_mw latitude longitude primary_fuel
1     AFG  Afghanistan          33   32.322   65.1190        Hydro
2     AFG  Afghanistan          10   31.670   65.7950        Solar
3     AFG  Afghanistan          10   31.623   65.7920        Solar
4     AFG  Afghanistan          66   34.556   69.4787        Hydro
5     AFG  Afghanistan         100   34.641   69.7170        Hydro</code></pre>
</div>
</div>
<p><strong>Description</strong></p>
<p>The dataset includes detailed information on power plants worldwide (34,936 observations and 36 variables), such as:</p>
<ul>
<li>Location (latitude, longitude, country).</li>
<li>Capacity (capacity_mw).</li>
<li>Primary and secondary fuel types.</li>
</ul>
</section>
<section id="point-map-of-resources" class="level2">
<h2 class="anchored" data-anchor-id="point-map-of-resources">Point Map of Resources</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_3_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The point map illustrates the geographic distribution of power plants globally, categorized by primary fuel types such as coal, solar, wind, hydro, and nuclear:</p>
<ol type="1">
<li>Energy Infrastructure Patterns:
<ul>
<li><p>Developed regions (e.g., North America, Europe, East Asia) exhibit dense concentrations of power plants with a diverse mix of fuel types.</p></li>
<li><p>Developing regions, particularly in Africa and parts of South America, show sparser distributions of power plants.</p></li>
</ul></li>
<li>Fuel Source Distribution:
<ul>
<li><p>Renewable energy sources like wind, solar, and hydro are broadly distributed across regions.</p></li>
<li><p>Fossil fuel power plants dominate in industrialized regions.</p></li>
</ul></li>
</ol>
<p>These patterns highlight disparities in energy infrastructure and the varying reliance on renewable versus fossil fuel sources worldwide.</p>
<hr>
</section>
</section>
<section id="spatial-analysis" class="level1">
<h1>Spatial Analysis</h1>
<section id="morans-i" class="level2">
<h2 class="anchored" data-anchor-id="morans-i">Moran’s I</h2>
<section id="global-morans-i-of-conflicts" class="level3">
<h3 class="anchored" data-anchor-id="global-morans-i-of-conflicts">Global Moran’s I of Conflicts</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  grid_aggregated$total_fatalities  
weights: weights_conflict  
n reduced by no-neighbour observations  

Moran I statistic standard deviate = 35.089, p-value &lt; 2.2e-16
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
     3.816430e-02     -9.112448e-05      1.188626e-06 </code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The analysis reveals significant spatial autocorrelation in conflict fatalities across the study area:</p>
<ol type="1">
<li>Spatial Association: A Moran’s I statistic of 0.038 indicates a positive spatial association, where high-fatality areas tend to cluster near other high-fatality areas, and low-fatality areas cluster near low-fatality areas.</li>
<li>Statistical Significance: The extremely low p-value <span class="math inline">\((&lt; 2.2 \times 10^{-16})\)</span> confirms that this clustering is highly significant and not due to random chance. A z-score of 35.089 underscores the strength of this spatial pattern.</li>
<li>Implications: Conflict fatalities are not randomly distributed but concentrated in specific regions, likely driven by geographic, political, or socio-economic factors.</li>
</ol>
<p>These findings highlight the importance of underlying spatial processes in shaping the distribution of conflict fatalities.</p>
</section>
<section id="local-morans-i-of-conflicts" class="level3">
<h3 class="anchored" data-anchor-id="local-morans-i-of-conflicts">Local Moran’s I of Conflicts</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    grid_id       total_fatalities            geometry     local_moran       
 Min.   :   183   Min.   :    0.00   MULTIPOINT   :5815   Min.   : -38.2770  
 1st Qu.: 89096   1st Qu.:    0.00   POINT        :5184   1st Qu.:   0.0195  
 Median :108914   Median :    2.00   epsg:3857    :   0   Median :   0.3689  
 Mean   :113034   Mean   :   49.48   +proj=merc...:   0   Mean   :   4.5918  
 3rd Qu.:140496   3rd Qu.:   13.00                        3rd Qu.:   0.7493  
 Max.   :247024   Max.   :28639.00                        Max.   :3089.6037  
                                                                             
    p_value       significance    cluster_type      
 Min.   :0.0000   Mode :logical   Length:10999      
 1st Qu.:0.3410   FALSE:10050     Class :character  
 Median :0.5009   TRUE :925       Mode  :character  
 Mean   :0.4886   NA's :24                          
 3rd Qu.:0.6642                                     
 Max.   :0.9999                                     
 NA's   :24                                         </code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The analysis reveals significant spatial patterns in conflict fatalities:</p>
<ol type="1">
<li>Distribution of Fatalities: Fatalities range from 0 to 28,639, with a mean of 49.48, indicating a highly skewed distribution where a small number of cells experience extreme conflict intensity.</li>
<li>Local Moran’s I Statistics: The Local Moran’s I statistic ranges from -38.28 to 3,089.60, showing both strong negative and positive spatial autocorrelation. The overall mean (4.59) suggests a tendency for clustering.</li>
<li>Clustering: 8.4% of grid cells (925) exhibit significant clustering (p &lt; 0.05), categorized as “High-High” (hotspots with high fatalities) or “Low-Low” (cold spots with low fatalities).</li>
<li>Non-Significant Cells: The majority (91.6%) of grid cells show no significant spatial clustering.</li>
</ol>
<p>The results highlight the uneven spatial distribution of conflict fatalities, with distinct hotspots of intense conflict and regions of relative stability. These patterns can guide further investigation into the drivers of conflict and geographic vulnerabilities.</p>
<p><strong>Visualization</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_3_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><a href="conflict_clusters_map.html">View the interactive map here</a></p>
<p>The analysis reveals distinct spatial patterns of conflict fatalities:</p>
<ol type="1">
<li>High-High Clusters (Red Dots): Hotspots of intense conflict activity are concentrated in regions like Central and South Asia (e.g., Afghanistan, Pakistan) and parts of Africa (e.g., Sudan, West Africa).</li>
<li>Low-Low Clusters (Blue Dots): Cold spots with minimal fatalities are found in areas such as Central Asia and parts of the Middle East, indicating either stability or sparse data.</li>
<li>Non-Significant Regions (Gray Dots): The majority of the map shows no statistically significant clustering, with fatalities either absent, isolated, or lacking strong spatial relationships. These regions include North and South America, much of Africa, and Southeast Asia.</li>
</ol>
<p>Localized clustering in conflict-prone areas is likely driven by factors such as political instability or resource competition. Globally, conflict fatalities exhibit weak spatial autocorrelation outside these hotspots. Local Moran’s I effectively identifies these clusters, providing valuable insights into the spatial dynamics of conflicts.</p>
</section>
<section id="global-morans-i-of-resources" class="level3">
<h3 class="anchored" data-anchor-id="global-morans-i-of-resources">Global Moran’s I of Resources</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  resources_sf$capacity_mw  
weights: weights  
n reduced by no-neighbour observations  

Moran I statistic standard deviate = 199.76, p-value &lt; 2.2e-16
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
     6.005299e-02     -2.864837e-05      9.046567e-08 </code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>Global Moran’s I reveals weak but statistically significant positive spatial autocorrelation (I = 0.060) for resource capacities. This means that locations with high resource capacities are slightly more likely to be near other high-capacity locations than expected under spatial randomness. The test strongly rejects the null hypothesis of no spatial autocorrelation <span class="math inline">\((p &lt; 2.2 \times 10^{-16})\)</span>, but the small magnitude of I indicates that the clustering effect is minimal. Overall, while there is a detectable spatial relationship, it is weak.</p>
</section>
<section id="local-morans-i-of-resources" class="level3">
<h3 class="anchored" data-anchor-id="local-morans-i-of-resources">Local Moran’s I of Resources</h3>
<p><strong>Visualization</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_3_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><a href="resources_clusters_map.html">View the interactive map here</a></p>
<p>The Local Moran’s I plot reveals significant spatial patterns in resource capacities.</p>
<ol type="1">
<li>High-High Clusters (Red Dots): These hotspots, observed in industrialized regions like central Europe, the southern U.S., parts of Canada, and resource-rich areas such as Brazil and Venezuela, represent areas with high resource capacities.</li>
<li>Low-Low Clusters (Blue Dots): Found in less industrialized regions, such as central and southern Africa and parts of central Asia, these indicate areas with consistently low resource capacities.</li>
<li>Outliers (Purple Dots): Scattered globally, these highlight regions where resource capacities differ significantly from their neighbors, such as industrial hubs or underdeveloped areas near high-capacity zones.</li>
<li>No Significant Clustering (Gray Dots): The majority of locations show no statistically significant spatial clustering.</li>
</ol>
<p>These patterns indicate that high-capacity clusters align with developed regions supported by robust energy infrastructure, low-capacity clusters are concentrated in less industrialized areas, and outliers reflect localized variability influenced by unique geographic or socio-economic factors.</p>
</section>
<section id="compare-conflict-and-resource-data" class="level3">
<h3 class="anchored" data-anchor-id="compare-conflict-and-resource-data">Compare conflict and resource data</h3>
<p>Compare conflict locations with the identified clusters to see if conflicts correlate with hotspots or cold spots.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 3 features and 3 fields
Geometry type: MULTIPOINT
Dimension:     XY
Bounding box:  xmin: -8741363 ymin: -2688083 xmax: 13983150 ymax: 7426823
Projected CRS: WGS 84 / Pseudo-Mercator
# A tibble: 3 × 4
  cluster_type    conflict_count                                geometry perce…¹
* &lt;chr&gt;                    &lt;int&gt;                        &lt;MULTIPOINT [m]&gt;   &lt;dbl&gt;
1 High-High                  375 ((-5180063 -2688083), (-4792738 -26110…   61.4 
2 Low-Low                     36 ((-7510993 880852.7), (5592880 3580380…    5.89
3 Not Significant            200 ((-8741363 -25592.42), (-169728.8 1387…   32.7 
# … with abbreviated variable name ¹​percentage</code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<ol type="1">
<li>Dominance of High-High Clusters: The majority of conflicts occur in High-High clusters, confirming the hypothesis that areas with a high concentration of resources are prone to conflicts.</li>
<li>Non-Clustered Areas: The substantial percentage of conflicts in Not Significant areas suggests that while resource concentration plays a significant role, other factors may drive conflicts in regions without significant clustering.</li>
<li>Low-Conflict Areas: The small percentage of conflicts in Low-Low clusters indicates that areas with low resource concentration are less likely to experience conflicts.</li>
</ol>
</section>
</section>
<section id="pairwise-correlation-function-pcf" class="level2">
<h2 class="anchored" data-anchor-id="pairwise-correlation-function-pcf">Pairwise Correlation Function (PCF)</h2>
<section id="pcf-of-observed-data" class="level3">
<h3 class="anchored" data-anchor-id="pcf-of-observed-data">PCF of Observed Data</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_3_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The Pairwise Correlation Function (PCF) plot reveals a strong spatial relationship between conflicts and resource sites, with significant clustering at short distances.</p>
<ol type="1">
<li>Intense Clustering at 0–20 km: The PCF exceeds 25, indicating intense clustering of conflicts near resource sites.</li>
<li>Weakened Clustering at 20–50 km: The clustering effect diminishes but remains significant (PCF &gt; 1).</li>
<li>Randomness Beyond 50 km: The PCF approaches 1, suggesting a transition to spatial randomness and reduced influence of resource sites.</li>
</ol>
<p>These findings strongly support the hypothesis that conflicts are more likely to occur within a 50-km radius of resource sites, with the most pronounced clustering observed at 0–20 km. Analyzing within a 100-km radius enhances resolution, confirming that the clustering effect fades rapidly beyond 50 km.</p>
</section>
<section id="pcf-for-simulation" class="level3">
<h3 class="anchored" data-anchor-id="pcf-for-simulation">PCF for Simulation</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_3_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>    Distance         Observed      Theoretical   LowerBound    
 Min.   :     0   Min.   :3.968   Min.   :1    Min.   :0.9250  
 1st Qu.: 25000   1st Qu.:4.977   1st Qu.:1    1st Qu.:0.9438  
 Median : 50000   Median :6.749   Median :1    Median :0.9491  
 Mean   : 50000   Mean   :  Inf   Mean   :1    Mean   :1.1336  
 3rd Qu.: 75000   3rd Qu.:9.474   3rd Qu.:1    3rd Qu.:0.9509  
 Max.   :100000   Max.   :  Inf   Max.   :1    Max.   :8.0957  
                                               NA's   :1       
   UpperBound    
 Min.   : 1.043  
 1st Qu.: 1.056  
 Median : 1.063  
 Mean   : 1.342  
 3rd Qu.: 1.136  
 Max.   :10.535  
 NA's   :1       </code></pre>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The plot illustrates the spatial relationship between resource sites and conflicts, with the observed PCF <span class="math inline">\((g^\text{obs})\)</span> showing strong clustering at short distances.</p>
<ol type="1">
<li>Significant Clustering at 0–50 km: The observed PCF far exceeds the upper confidence bound within this range, peaking at over 100 around 5 km, indicating statistically significant clustering near resource sites.</li>
<li>Diminishing Clustering Beyond 20–50 km: The clustering effect gradually weakens as the distance increases, with the PCF declining beyond 20–50 km.</li>
<li>Transition to Randomness at 50–100 km: Beyond 50 km, the PCF aligns with the theoretical PCF <span class="math inline">\((g^\text{theo})\)</span> and falls within the confidence envelope, indicating a transition to randomness.</li>
</ol>
<p>These results strongly support the hypothesis that conflicts are significantly clustered within 50 km of resource sites, with the most intense clustering observed within 20 km. At greater distances, resource influence diminishes, leading to random spatial patterns.</p>
</section>
<section id="compare-pcf-of-observed-data-and-simulation" class="level3">
<h3 class="anchored" data-anchor-id="compare-pcf-of-observed-data-and-simulation">Compare PCF of Observed Data and Simulation</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>    Distance         Observed         LowerBound       UpperBound    
 Min.   :  1000   Min.   :  3.968   Min.   :0.9250   Min.   : 1.043  
 1st Qu.: 25750   1st Qu.:  4.964   1st Qu.:0.9438   1st Qu.: 1.056  
 Median : 50500   Median :  6.706   Median :0.9491   Median : 1.063  
 Mean   : 50500   Mean   :  9.828   Mean   :1.1336   Mean   : 1.342  
 3rd Qu.: 75250   3rd Qu.:  9.352   3rd Qu.:0.9509   3rd Qu.: 1.136  
 Max.   :100000   Max.   :111.524   Max.   :8.0957   Max.   :10.535  
                                                                     
     trans             iso        
 Min.   : 3.985   Min.   : 3.968  
 1st Qu.: 4.932   1st Qu.: 4.916  
 Median : 6.553   Median : 6.538  
 Mean   : 8.111   Mean   : 8.095  
 3rd Qu.: 8.941   3rd Qu.: 8.926  
 Max.   :26.114   Max.   :26.088  
 NA's   :80       NA's   :80      </code></pre>
</div>
</div>
<p><strong>Visulization</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="final_3_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong></p>
<p>The comparison between the observed PCF and simulated confidence bounds reveals statistically significant clustering of conflicts near resource sites.</p>
<ol type="1">
<li>Clustering at Short Distances (1–50 km): The observed PCF far exceeds the upper bound of simulations at smaller distances, with values such as 4.346 compared to an upper bound of 1.026, indicating strong clustering.</li>
<li>Diminishing Effect with Distance: As the distance increases, the clustering effect weakens, but the observed PCF still remains above the confidence bounds up to 100 km, though the gap gradually narrows.</li>
<li>Transition Toward Randomness Beyond 50 km: Beyond 50 km, the clustering effect diminishes significantly, with the spatial pattern moving closer to randomness.</li>
<li>Potential Edge Effects: The presence of NA values at larger distances suggests potential edge effects or sparse data in certain regions.</li>
</ol>
<hr>
</section>
</section>
</section>
<section id="initial-conclusion" class="level1">
<h1>Initial Conclusion</h1>
<p><strong>Hypothesis:</strong> “Countries with higher concentrations of natural resources are more likely to experience conflicts within a 50-km radius of the resource site.”</p>
<section id="findings" class="level2">
<h2 class="anchored" data-anchor-id="findings">Findings</h2>
<p>Based on the results of the Pairwise Correlation Function (PCF) analysis and Monte Carlo simulations:</p>
<ol type="1">
<li>Clustering at Short Distances (0–50 km):
<ul>
<li><p>The observed PCF values are significantly higher than the theoretical value of 1 and exceed the upper bound of the Monte Carlo confidence envelope at distances up to 50 km.</p></li>
<li><p>This confirms statistically significant clustering of conflicts near resource sites.</p></li>
<li><p>The clustering is strongest within 0–20 km, where the observed PCF reaches its peak.</p></li>
</ul></li>
<li>Transition to Randomness Beyond 50 km:
<ul>
<li><p>The observed PCF decreases with distance, indicating that the spatial influence of resource sites on conflicts diminishes gradually.</p></li>
<li><p>While clustering remains significant even beyond 50 km, the magnitude of clustering becomes weaker, approaching randomness at distances closer to 100 km.</p>
<ol start="3" type="1">
<li>Support for Hypothesis:</li>
</ol></li>
<li><p>The results provide strong evidence to support the hypothesis that conflicts are more likely to occur near resource sites within 50 km.</p></li>
<li><p>The effect is most pronounced at very short distances (0–20 km), suggesting that proximity to resources significantly increases the likelihood of conflicts.</p></li>
</ul></li>
</ol>
</section>
<section id="implications" class="level2">
<h2 class="anchored" data-anchor-id="implications">Implications</h2>
<ol type="1">
<li>Localized Resource-Driven Conflicts:
<ul>
<li>The results suggest that natural resource sites act as focal points for conflicts, particularly within 50 km, likely due to disputes over access, control, and exploitation of resources.</li>
</ul></li>
<li>Broader Influence of Resource Sites:
<ul>
<li>While the clustering effect weakens beyond 50 km, the continued significance of the observed PCF suggests that resource-related factors may still influence conflict dynamics at larger spatial scales.</li>
</ul></li>
</ol>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">Limitations</h2>
<ol type="1">
<li>Edge Effects and Data Sparsity:
<ul>
<li>The presence of Inf and NA values in the PCF calculations at larger distances indicates potential edge effects or sparse data in certain areas, which may affect the precision of results.</li>
</ul></li>
<li>Global Aggregation:
<ul>
<li>Analyzing data at the global scale may obscure regional variations or country-specific dynamics. Future work could focus on regional subsets to identify localized patterns.</li>
</ul></li>
<li>Temporal Dynamics:
<ul>
<li>This analysis does not consider the timing of conflicts and resource discoveries. A temporal analysis might reveal further insights into causality.</li>
</ul></li>
</ol>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>The analysis provides strong statistical evidence to support the hypothesis. Conflicts are significantly more likely to cluster near natural resource sites, particularly within 50 km. The clustering effect is strongest at distances less than 20 km but remains statistically significant up to 50 km and even beyond. This highlights the critical role of natural resource sites in driving localized conflict dynamics.</p>
<hr>
</section>
</section>
<section id="roadmap-for-further-exploration-and-refinement" class="level1">
<h1>Roadmap for Further Exploration and Refinement</h1>
<p>To build upon the initial conclusions and further validate or refine the findings, the following next steps are recommended. Future studies could analyze conflict-resource patterns across regions and resource types to uncover variations and explore temporal dynamics to examine causality between resource development and conflicts. Additional factors, such as socio-political and economic variables, could also be incorporated into the analysis to deepen understanding of the resource-conflict relationship.</p>
<p><strong>Key Steps:</strong></p>
<ul>
<li><p>Regional and Subtype Analysis: Examine variations in conflict-resource clustering across different regions and resource types.</p></li>
<li><p>Statistical Robustness: Validate findings and address potential biases to ensure reliability.</p></li>
<li><p>Hypothesis Refinement: Refine the initial hypothesis for greater specificity based on early insights.</p></li>
<li><p>Broader Contextual Factors: Include socio-political and economic variables to provide a more comprehensive analysis.</p></li>
<li><p>Refining Visualizations: Enhance clarity and interpretability of data visualizations for communication.</p></li>
<li><p>Policy Implications: Translate findings into actionable recommendations for policymakers.</p></li>
</ul>
<hr>
</section>
<section id="references" class="level1">
<h1>References</h1>
<ul>
<li>ACLED Data: https://acleddata.com</li>
<li>Global Power Plant Database: https://resourcewatch.org</li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>